stages:
  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/sonar_data.csv
    outs:
      - models/model.pkl
      - models/scaler.pkl
    metrics:
      - mlflow.db:
          cache: false
