events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name api.python-community.com mlflow.python-community.com;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 200 'SSL initialization in progress...';
            add_header Content-Type text/plain;
        }
    }
}
